default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ml_traning_development

test:
  <<: *default
  database: ml_traning_test
  username: root
  password: postgres
  host: 127.0.0.1

production:
  <<: *default
  database: ml_traning_production
  username: backend
  password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>
