default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ml_traning_development

test:
  <<: *default
  database: ml_traning_test
  username: <%= ENV.fetch("POSTGRES_HOST", '') %>
  password: <%= ENV.fetch("POSTGRES_HOST", '') %>
  host: <%= ENV.fetch("POSTGRES_HOST", '') %>

production:
  <<: *default
  database: ml_traning_production
  username: backend
  password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>
